# Generated by Django 5.2.1 on 2025-05-11 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_played", models.DateTimeField(auto_now_add=True)),
                (
                    "style",
                    models.PositiveSmallIntegerField(
                        choices=[(3, "三人麻雀"), (4, "四人麻雀")]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("score_unit", models.IntegerField(default=100)),
                ("chip_unit", models.IntegerField(default=500)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScoreEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("chip", models.IntegerField()),
                ("revenue", models.IntegerField(blank=True, null=True)),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="api.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.PositiveSmallIntegerField(
                        choices=[(3, "三人麻雀"), (4, "四人麻雀")]
                    ),
                ),
                ("total_games", models.IntegerField(default=0)),
                ("rank_1", models.IntegerField(default=0)),
                ("rank_2", models.IntegerField(default=0)),
                ("rank_3", models.IntegerField(default=0)),
                ("rank_4", models.IntegerField(default=0)),
                ("average_rank", models.FloatField(blank=True, null=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("average_revenue", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="api.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "style")},
            },
        ),
    ]
